volumes:
    mysql:

networks:
    backend:
    
services:
    mysql:
        image: mysql:8
        container_name: mysql
        volumes:
        - mysql:/var/lib/mysql
        networks:
            backend:
                aliases:
                    - mysql
        environment:
        - MYSQL_DATABASE=superheroes
        - MYSQL_USER=sa
        - MYSQL_ROOT_PASSWORD=admin
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3

    backend:
        image: back:2.0
        build: ./java
        container_name: backend
        networks:
            backend:
                aliases:
                    - backend
        environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/superheroes
        - SPRING_DATASOURCE_USERNAME=sa
        - SPRING_DATASOURCE_PASSWORD=admin
        ports:
        - 8448:8448
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "localhost:8448"]
            interval: 15s
            timeout: 5s
            retries: 3

    frontend:
      image: front:2.0
      build: ./angular
      container_name: frontend
      environment:
      - BACKEND_URL_ENV_VAR=http://localhost:8448
      ports:
      - 80:80
      depends_on:
          backend:
              condition: service_healthy
      healthcheck:
          test: ["CMD", "curl", "localhost:80"]
          interval: 5s
          timeout: 5s
          retries: 2